In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("C:/Users/nihal/OneDrive/Documents/jupyter/jupyter notebook/Water_quality prediction/water_potability.csv")
print(df.head())

         ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0  


In [3]:
print("\nDataset Shape:")
print(df.shape)




Dataset Shape:
(3276, 10)


In [4]:
print("\nDataset Information:")
print(df.info())


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB
None


In [5]:
print("\nStatistical Summary:")
print(df.describe())


Statistical Summary:
                ph     Hardness        Solids  Chloramines      Sulfate  \
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   
mean      7.080795   196.369496  22014.092526     7.122277   333.775777   
std       1.594320    32.879761   8768.570828     1.583085    41.416840   
min       0.000000    47.432000    320.942611     0.352000   129.000000   
25%       6.093092   176.850538  15666.690297     6.127421   307.699498   
50%       7.036752   196.967627  20927.833607     7.130299   333.073546   
75%       8.062066   216.667456  27332.762127     8.114887   359.950170   
max      14.000000   323.124000  61227.196008    13.127000   481.030642   

       Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability  
count   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000  
mean     426.205111       14.284970        66.396293     3.966786     0.390110  
std       80.824064        3.308162        16.175008     0.

In [6]:
print("\nDuplicate Rows:", df.duplicated().sum())


Duplicate Rows: 0


In [7]:
print("\nMissing Values:")
print(df.isnull().sum())


Missing Values:
ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64


In [8]:
for column in df.columns:
    if df[column].isnull().sum() > 0:
        df[column].fillna(df[column].median(), inplace=True)

C:\Users\nihal\AppData\Local\Temp\ipykernel_18700\3954296751.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)
C:\Users\nihal\AppData\Local\Temp\ipykernel_18700\3954296751.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For

In [9]:
print("\nMissing Values After Treatment:")
print(df.isnull().sum())


Missing Values After Treatment:
ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64


In [10]:
X = df.drop("Potability", axis=1)
y = df["Potability"]

In [11]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [12]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print("\nScaled Features:")
print(X_scaled.head())


Scaled Features:
         ph  Hardness    Solids  Chloramines   Sulfate  Conductivity  \
0 -0.025474  0.259195 -0.139471     0.112415  0.965957      1.708954   
1 -2.284717 -2.036414 -0.385987    -0.307694 -0.014799      2.062575   
2  0.697319  0.847665 -0.240047     1.360594 -0.014799     -0.094032   
3  0.845393  0.547651  0.000493     0.592008  0.644130     -0.778830   
4  1.372982 -0.464429 -0.460249    -0.363698 -0.649522     -0.343939   

   Organic_carbon  Trihalomethanes  Turbidity  
0       -1.180651         1.305434  -1.286298  
1        0.270597        -0.639186   0.684218  
2        0.781117         0.000800  -1.167365  
3        1.255134         2.152154   0.848412  
4       -0.824357        -2.182297   0.138786  


In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Set Shape:", X_train.shape)
print("Testing Set Shape :", X_test.shape)


Training Set Shape: (2620, 9)
Testing Set Shape : (656, 9)


In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

model = LogisticRegression(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1-Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.6097560975609756
Precision: 0.0
Recall   : 0.0
F1-Score : 0.0
ROC-AUC  : 0.548466796875

Confusion Matrix
[[400   0]
 [256   0]]

Classification Report
              precision    recall  f1-score   support

           0       0.61      1.00      0.76       400
           1       0.00      0.00      0.00       256

    accuracy                           0.61       656
   macro avg       0.30      0.50      0.38       656
weighted avg       0.37      0.61      0.46       656



C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.5960365853658537
Precision: 0.48132780082987553
Recall   : 0.453125
F1 Score : 0.46680080482897385
ROC AUC  : 0.5703125
[[275 125]
 [140 116]]
              precision    recall  f1-score   support

           0       0.66      0.69      0.67       400
           1       0.48      0.45      0.47       256

    accuracy                           0.60       656
   macro avg       0.57      0.57      0.57       656
weighted avg       0.59      0.60      0.59       656



In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.6585365853658537
Precision: 0.6311475409836066
Recall   : 0.30078125
F1 Score : 0.4074074074074074
ROC AUC  : 0.6406689453125001
[[355  45]
 [179  77]]
              precision    recall  f1-score   support

           0       0.66      0.89      0.76       400
           1       0.63      0.30      0.41       256

    accuracy                           0.66       656
   macro avg       0.65      0.59      0.58       656
weighted avg       0.65      0.66      0.62       656



In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.6189024390243902
Precision: 0.5185185185185185
Recall   : 0.328125
F1 Score : 0.4019138755980861
ROC AUC  : 0.601513671875
[[322  78]
 [172  84]]
              precision    recall  f1-score   support

           0       0.65      0.81      0.72       400
           1       0.52      0.33      0.40       256

    accuracy                           0.62       656
   macro avg       0.59      0.57      0.56       656
weighted avg       0.60      0.62      0.60       656



In [38]:
from sklearn.svm import SVC
from sklearn.metrics import *

model = SVC(
    kernel='rbf',
    probability=True,
    random_state=42
)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.6707317073170732
Precision: 0.7040816326530612
Recall   : 0.26953125
F1 Score : 0.3898305084745763
ROC AUC  : 0.648671875
[[371  29]
 [187  69]]
              precision    recall  f1-score   support

           0       0.66      0.93      0.77       400
           1       0.70      0.27      0.39       256

    accuracy                           0.67       656
   macro avg       0.68      0.60      0.58       656
weighted avg       0.68      0.67      0.62       656



In [21]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

model = GaussianNB()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy : 0.614329268292683
Precision: 0.5161290322580645
Recall   : 0.1875
F1 Score : 0.27507163323782235
ROC AUC  : 0.6090332031250001
[[355  45]
 [208  48]]
              precision    recall  f1-score   support

           0       0.63      0.89      0.74       400
           1       0.52      0.19      0.28       256

    accuracy                           0.61       656
   macro avg       0.57      0.54      0.51       656
weighted avg       0.59      0.61      0.56       656



In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd

models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(probability=True, random_state=42),
    "Naive Bayes": GaussianNB(),
    "gradient": GradientBoostingClassifier()
}

results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]

    results.append([
        name,
        accuracy_score(y_test,y_pred),
        precision_score(y_test,y_pred),
        recall_score(y_test,y_pred),
        f1_score(y_test,y_pred),
        roc_auc_score(y_test,y_prob)
    ])

results_df = pd.DataFrame(results, columns=[
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1-Score",
    "ROC-AUC"
])

print(results_df.sort_values(by="Accuracy", ascending=False))

C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nihal\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision

                 Model  Accuracy  Precision    Recall  F1-Score   ROC-AUC
6             gradient  0.809451   0.857923  0.613281  0.715262  0.891279
2        Random Forest  0.800305   0.830688  0.613281  0.705618  0.871123
1        Decision Tree  0.751524   0.685259  0.671875  0.678501  0.737187
0  Logistic Regression  0.609756   0.000000  0.000000  0.000000  0.569482
4                  SVM  0.609756   0.000000  0.000000  0.000000  0.527734
5          Naive Bayes  0.609756   0.500000  0.179688  0.264368  0.608760
3                  KNN  0.571646   0.430939  0.304688  0.356979  0.524873


In [ ]:
pip install xgboost

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import *

model = XGBClassifier(
    eval_metric='logloss',
    random_state=42
)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall   :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print("ROC AUC  :", roc_auc_score(y_test,y_prob))

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, confusion_matrix

# Load and Handle Null Data
df = pd.read_csv('water_potability.csv')
df['ph'] = df.groupby('Potability')['ph'].transform(lambda x: x.fillna(x.median()))
df['Sulfate'] = df.groupby('Potability')['Sulfate'].transform(lambda x: x.fillna(x.median()))
df['Trihalomethanes'] = df.groupby('Potability')['Trihalomethanes'].transform(lambda x: x.fillna(x.median()))

# Split and Scale
X = df.drop('Potability', axis=1)
y = df['Potability']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training & Evaluation
model = GradientBoostingClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

print("=== GRADIENT BOOSTING RESULTS ===")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, zero_division=0):.4f}")
print(f"F1-Score:  {f1_score(y_test, y_pred, zero_division=0):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test, y_prob):.4f}")

# Random Input Test
random_input = pd.DataFrame([{'ph': 7.2, 'Hardness': 210.5, 'Solids': 18500.3, 'Chloramines': 6.8, 'Sulfate': 320.1, 'Conductivity': 450.0, 'Organic_carbon': 12.5, 'Trihalomethanes': 70.4, 'Turbidity': 4.1}])
random_scaled = scaler.transform(random_input)
print(f"Random Input Prediction: {model.predict(random_scaled)[0]}")
if {model.predict(random_scaled)[0]}==1:
  print("The water is safe to drink")
else:
  print("The water is not safe to drink")

In [14]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# ==========================
# Load Dataset
# ==========================

df = pd.read_csv("water_potability.csv")

# ==========================
# Handle Missing Values
# ==========================

df["ph"] = df.groupby("Potability")["ph"].transform(
    lambda x: x.fillna(x.median())
)

df["Sulfate"] = df.groupby("Potability")["Sulfate"].transform(
    lambda x: x.fillna(x.median())
)

df["Trihalomethanes"] = df.groupby("Potability")["Trihalomethanes"].transform(
    lambda x: x.fillna(x.median())
)

# ==========================
# Features & Target
# ==========================

X = df.drop("Potability", axis=1)
y = df["Potability"]

# ==========================
# Train Test Split
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# ==========================
# Feature Scaling
# ==========================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ==========================
# Gradient Boosting Model
# ==========================

model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

model.fit(X_train_scaled, y_train)

# ==========================
# Predictions
# ==========================

y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

# ==========================
# Evaluation
# ==========================

print("="*50)
print("GRADIENT BOOSTING RESULTS")
print("="*50)

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

print()

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

print()

print(classification_report(y_test, y_pred))

# ==========================
# Save Model
# ==========================

joblib.dump(model, "gradient_boosting_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("\nModel Saved Successfully!")
print("gradient_boosting_model.pkl")
print("scaler.pkl")

# ==========================
# Random Prediction
# ==========================

sample = pd.DataFrame([{
    "ph":7.2,
    "Hardness":210.5,
    "Solids":18500.3,
    "Chloramines":6.8,
    "Sulfate":320.1,
    "Conductivity":450,
    "Organic_carbon":12.5,
    "Trihalomethanes":70.4,
    "Turbidity":4.1
}])

sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)[0]

print("\nPrediction:", prediction)

if prediction == 1:
    print("Water is SAFE to drink")
else:
    print("Water is NOT SAFE to drink")

GRADIENT BOOSTING RESULTS
Confusion Matrix
[[375  25]
 [ 99 157]]

Accuracy : 0.8109756097560976
Precision: 0.8626373626373627
Recall   : 0.61328125
F1 Score : 0.7168949771689498
ROC AUC  : 0.89126953125

              precision    recall  f1-score   support

           0       0.79      0.94      0.86       400
           1       0.86      0.61      0.72       256

    accuracy                           0.81       656
   macro avg       0.83      0.78      0.79       656
weighted avg       0.82      0.81      0.80       656


Model Saved Successfully!
gradient_boosting_model.pkl
scaler.pkl

Prediction: 0
Water is NOT SAFE to drink


In [42]:
from sklearn.model_selection import GridSearchCV

# ==========================
# Grid Search
# ==========================

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [2, 3, 4],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_search = GridSearchCV(
    estimator=GradientBoostingClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(X_train_scaled, y_train)

print("="*50)
print("GRID SEARCH RESULTS")
print("="*50)
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

# Best Model
model = grid_search.best_estimator_

GRID SEARCH RESULTS
Best Parameters: {'learning_rate': 0.05, 'max_depth': 4, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
Best Accuracy: 0.7893129770992365


In [43]:
from sklearn.model_selection import RandomizedSearchCV

# ==========================
# Random Search
# ==========================

param_dist = {
    'n_estimators': [100,150,200,250,300,350,400],
    'learning_rate': [0.01,0.03,0.05,0.07,0.1,0.2],
    'max_depth': [2,3,4,5,6],
    'min_samples_split': [2,4,6,8,10],
    'min_samples_leaf': [1,2,3,4]
}

random_search = RandomizedSearchCV(
    estimator=GradientBoostingClassifier(random_state=42),
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_scaled, y_train)

print("="*50)
print("RANDOM SEARCH RESULTS")
print("="*50)
print("Best Parameters:", random_search.best_params_)
print("Best Accuracy:", random_search.best_score_)

# Best Model
model = random_search.best_estimator_

RANDOM SEARCH RESULTS
Best Parameters: {'n_estimators': 100, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'learning_rate': 0.1}
Best Accuracy: 0.7851145038167939
